version: '3'

networks:
  web-network:

services:
#  php-cli:
#    build:
#      context: ./php-cli
#    tty: true
#    volumes:
#      - ./app:/var/www
#    networks:
#      - web-network
#    working_dir: /var/www

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    tty: true
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web-network

  php-fpm:
    build:
      context: ./php-fpm
    container_name: php-fpm
    tty: true
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - web-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - web-network
